// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CurrencyconverterController from "./currencyconverter_controller"
application.register("currencyconverter", CurrencyconverterController)

import FullpageController from "./fullpage_controller"
application.register("fullpage", FullpageController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavlinksController from "./navlinks_controller"
application.register("navlinks", NavlinksController)
